          echo "===== 交换分区创建完成 ====="

      - name: Build toolchain (with progress)
        run: |
          echo "===== 开始编译工具链（预计1-2小时） ====="
          cd buildroot-2017.11.1
          export FORCE_UNSAFE_CONFIGURE=1
          # 拆分编译步骤，每步输出进度
          make toolchain -j2 V=1  # V=1 显示详细编译日志
          if [ $? -eq 0 ]; then
            echo "===== 工具链编译成功 ====="
          else
            echo "===== 工具链编译失败 ====="
            exit 1
          fi

      - name: Package toolchain
        run: |
          echo "===== 开始打包工具链 ====="
          cd buildroot-2017.11.1/output/host
          tar -czf ../../../armv7-toolchain.tar.gz *
          echo "===== 工具链打包完成 ====="

      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: armv7-toolchain
          path: buildroot-2017.11.1/armv7-toolchain.tar.gz
          retention-days: 30
