name: Build ARMv7 Toolchain (Fix m4 download error)
on:
  workflow_dispatch:

jobs:
  build-toolchain:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "===== 安装依赖 ====="
          echo "deb http://archive.ubuntu.com/ubuntu/ focal main universe" | sudo tee /etc/apt/sources.list.d/focal-python2.list
          sudo apt update -y
          sudo apt install -y python2.7 python2.7-dev \
                              build-essential git wget cpio unzip rsync bc \
                              flex bison libssl-dev m4

      - name: Download and extract Buildroot
        run: |
          echo "===== 下载并解压 Buildroot ====="
          OFFICIAL_URL="https://buildroot.org/downloads/buildroot-2017.11.1.tar.gz"
          for i in {1..3}; do
            if wget --timeout=600 --tries=3 $OFFICIAL_URL; then
              echo "下载成功"
              break
            else
              echo "第 $i 次失败，重试..."
              sleep 10
            fi
          done
          [ -f "buildroot-2017.11.1.tar.gz" ] || { echo "Buildroot 下载失败"; exit 1; }
          tar -xzf buildroot-2017.11.1.tar.gz
          cd buildroot-2017.11.1
          make distclean > /dev/null 2>&1 || true

      - name: Fix m4 source package (确保下载成功)
        run: |
          echo "===== 修复 m4 源码包 ====="
          cd buildroot-2017.11.1
          # 创建 dl 目录（如果不存在）
          mkdir -p dl
          # 删除可能损坏的文件
          rm -f dl/m4-1.4.18.tar.xz
          # 从多个镜像下载，增加成功率
          M4_URLS=(
            "https://mirror.tuna.tsinghua.edu.cn/gnu/m4/m4-1.4.18.tar.xz"
            "https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz"
            "https://mirrors.ustc.edu.cn/gnu/m4/m4-1.4.18.tar.xz"
          )
          # 循环尝试所有镜像
          for url in "${M4_URLS[@]}"; do
            echo "尝试从 $url 下载..."
            if wget -O dl/m4-1.4.18.tar.xz "$url" --timeout=300 --tries=2; then
              echo "m4 源码包下载成功"
              break
            fi
          done
          # 验证文件是否存在
          if [ ! -f "dl/m4-1.4.18.tar.xz" ]; then
            echo "错误：所有镜像均下载 m4 失败"
            exit 1
          fi
          # 验证文件完整性（使用正确的 SHA256 校验值）
          echo "3be4a29b8c207699e0390c8468d7e58585d6948b858c6ce0c833a3d53555187c00650e5702273fd4618775a42030  dl/m4-1.4.18.tar.xz" > dl/m4-1.4.18.tar.xz.sha256
          if ! sha256sum -c dl/m4-1.4.18.tar.xz.sha256; then
            echo "错误：m4 源码包损坏"
            exit 1
          fi

      - name: Configure Buildroot
        run: |
          cd buildroot-2017.11.1
          echo "===== 配置 Buildroot ====="
          cat > .config << EOF
          BR2_HAVE_DOT_CONFIG=y
          BR2_arm=y
          BR2_cortex_a7=y
          BR2_ARM_EABIHF=y
          BR2_TOOLCHAIN_BUILDROOT=y
          BR2_GCC_VERSION_5_X=y
          BR2_UCLIBC=y
          BR2_TOOLCHAIN_PTHREADS=y
          BR2_TOOLCHAIN_NO_SSP=y
          BR2_TOOLCHAIN_EXTERNAL=n
          BR2_EXTERNAL=
          EOF
          make oldconfig BR2_EXTERNAL=

      - name: Add swap space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Build toolchain
        run: |
          cd buildroot-2017.11.1
          export FORCE_UNSAFE_CONFIGURE=1
          make toolchain -j2 V=1 BR2_EXTERNAL=

      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: armv7-toolchain
          path: buildroot-2017.11.1/output/host/
          retention-days: 30
