name: Build ARMv7 Toolchain (Final Fix)
on:
  workflow_dispatch:

jobs:
  build-toolchain:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "===== 安装依赖 ====="
          echo "deb http://archive.ubuntu.com/ubuntu/ focal main universe" | sudo tee /etc/apt/sources.list.d/focal-python2.list
          sudo apt update -y
          sudo apt install -y python2.7 python2.7-dev \
                              build-essential git wget cpio unzip rsync bc \
                              flex bison libssl-dev

      - name: Download and extract Buildroot
        run: |
          echo "===== 下载并解压 Buildroot ====="
          OFFICIAL_URL="https://buildroot.org/downloads/buildroot-2017.11.1.tar.gz"
          for i in {1..3}; do
            if wget --timeout=600 --tries=3 $OFFICIAL_URL; then
              echo "下载成功"
              break
            else
              echo "第 $i 次失败，重试..."
              sleep 10
            fi
          done
          [ -f "buildroot-2017.11.1.tar.gz" ] || { echo "下载失败"; exit 1; }
          tar -xzf buildroot-2017.11.1.tar.gz
          # 清除旧配置缓存
          cd buildroot-2017.11.1
          make distclean > /dev/null 2>&1 || true

      - name: Configure Buildroot (禁用外部树)
        run: |
          cd buildroot-2017.11.1
          echo "===== 配置 Buildroot ====="
          cat > .config << EOF
          BR2_HAVE_DOT_CONFIG=y
          BR2_arm=y
          BR2_cortex_a7=y
          BR2_ARM_EABIHF=y
          BR2_TOOLCHAIN_BUILDROOT=y
          BR2_GCC_VERSION_5_X=y
          BR2_UCLIBC=y
          BR2_TOOLCHAIN_PTHREADS=y
          BR2_TOOLCHAIN_NO_SSP=y
          # 明确禁用外部工具链和外部树
          BR2_TOOLCHAIN_EXTERNAL=n
          BR2_EXTERNAL=
          EOF
          # 强制更新配置，忽略外部依赖
          make oldconfig BR2_EXTERNAL=

      - name: Add swap space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Build toolchain
        run: |
          cd buildroot-2017.11.1
          export FORCE_UNSAFE_CONFIGURE=1
          # 编译时明确指定无外部树
          make toolchain -j2 V=1 BR2_EXTERNAL=

      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: armv7-toolchain
          path: buildroot-2017.11.1/output/host/
          retention-days: 30
