name: Build ARMv7 Toolchain (fix python2.7-dev)
on:
  workflow_dispatch:

jobs:
  build-toolchain:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (with Python 2.7)
        run: |
          echo "===== 安装依赖（含 Python 2.7） ====="
          # 添加 Ubuntu 20.04 的 Python 2.7 源（兼容新系统）
          echo "deb http://archive.ubuntu.com/ubuntu/ focal main universe" | sudo tee /etc/apt/sources.list.d/focal-python2.list
          # 刷新源并优先使用 focal 源的 Python 2.7 包
          sudo apt update -y
          # 安装 Python 2.7 及开发包
          sudo apt install -y python2.7 python2.7-dev
          # 安装其他依赖
          sudo apt install -y build-essential git wget cpio unzip rsync bc \
                              flex bison libssl-dev

      - name: Download Buildroot 2017.11.1 (with retry)
        run: |
          echo "===== 下载 Buildroot 源码 ====="
          for i in {1..3}; do
            if wget --timeout=600 --tries=3 https://buildroot.org/downloads/buildroot-2017.11.1.tar.gz; then
              echo "下载成功"
              break
            else
              echo "第 $i 次下载失败，重试..."
              sleep 10
            fi
          done
          if [ ! -f "buildroot-2017.11.1.tar.gz" ]; then
            echo "错误：Buildroot 源码下载失败"
            exit 1
          fi
          tar -xzf buildroot-2017.11.1.tar.gz

      - name: Configure ARMv7 toolchain
        run: |
          cd buildroot-2017.11.1
          cat > .config << EOF
          BR2_arm=y
          BR2_cortex_a7=y
          BR2_ARM_EABIHF=y
          BR2_TOOLCHAIN_BUILDROOT=y
          BR2_GCC_VERSION_5_X=y
          BR2_UCLIBC=y
          BR2_TOOLCHAIN_EXTERNAL=y
          BR2_TOOLCHAIN_PTHREADS=y
          BR2_TOOLCHAIN_NO_SSP=y
          EOF
          make oldconfig

      - name: Add swap space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Build toolchain
        run: |
          cd buildroot-2017.11.1
          export FORCE_UNSAFE_CONFIGURE=1
          make toolchain -j2 V=1

      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: armv7-toolchain
          path: buildroot-2017.11.1/armv7-toolchain.tar.gz
          retention-days: 30
