name: Build ARMv7 Toolchain (fixed exit code 100)
on:
  workflow_dispatch:

jobs:
  build-toolchain:
    runs-on: ubuntu-latest  # 换用资源更充足的镜像
    timeout-minutes: 180
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "===== 安装依赖 ====="
          sudo apt update -y
          sudo apt install -y build-essential git wget cpio unzip rsync bc \
                              flex bison libssl-dev python2.7-dev

      - name: Download Buildroot 2017.11.1 (with retry)
        run: |
          echo "===== 下载 Buildroot 源码（带重试） ====="
          # 添加重试机制（最多 3 次）和超时控制（10分钟）
          for i in {1..3}; do
            if wget --timeout=600 --tries=3 https://buildroot.org/downloads/buildroot-2017.11.1.tar.gz; then
              echo "下载成功"
              break
            else
              echo "第 $i 次下载失败，重试..."
              sleep 10
            fi
          done
          # 若3次都失败则退出
          if [ ! -f "buildroot-2017.11.1.tar.gz" ]; then
            echo "错误：Buildroot 源码下载失败"
            exit 1
          fi
          # 验证文件完整性（可选，防止下载损坏）
          tar -tzf buildroot-2017.11.1.tar.gz > /dev/null || {
            echo "错误：文件损坏，重新下载"
            exit 1
          }
          tar -xzf buildroot-2017.11.1.tar.gz
          cd buildroot-2017.11.1

      # 后续步骤（配置/编译）不变...
      - name: Configure ARMv7 toolchain
        run: |
          echo "===== 配置工具链 ====="
          cd buildroot-2017.11.1
          cat > .config << EOF
          BR2_arm=y
          BR2_cortex_a7=y
          BR2_ARM_EABIHF=y
          BR2_TOOLCHAIN_BUILDROOT=y
          BR2_GCC_VERSION_5_X=y
          BR2_UCLIBC=y
          BR2_TOOLCHAIN_EXTERNAL=y
          BR2_TOOLCHAIN_PTHREADS=y
          BR2_TOOLCHAIN_NO_SSP=y
          EOF
          make oldconfig

      - name: Add swap space
        run: |
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Build toolchain
        run: |
          cd buildroot-2017.11.1
          export FORCE_UNSAFE_CONFIGURE=1
          make toolchain -j2 V=1

      - name: Package and upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: armv7-toolchain
          path: buildroot-2017.11.1/armv7-toolchain.tar.gz
          retention-days: 30
